MACRO(SUBDIRLIST result curdir)
    FILE(GLOB_RECURSE children LIST_DIRECTORIES true RELATIVE ${curdir} ${curdir}/*)
    SET(dirlist "")
    FOREACH (child ${children})
        IF (IS_DIRECTORY ${curdir}/${child})
            file(GLOB files ${curdir}/${child}/*.h ${curdir}/${child}/*.hpp)
            if (files)
                LIST(APPEND dirlist ${child})
            endif ()
        ENDIF ()
    ENDFOREACH ()

    list(FILTER dirlist EXCLUDE REGEX cmake-build-debug*)
    SET(${result} ${dirlist})
ENDMACRO()
